apiVersion: v1
kind: Namespace
metadata:
  name: mySpace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-deployment
  namespace: mySpace
  labels:
    name: snake-deployment
    env: prod
    author: vikas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snake-pod
  template:
    metadata:
      labels:
        app: snake-pod
    spec:
      containers:
        - name: snake-container
          image: vikasprince/snake-game
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snake-hpa
  namespace: mySpace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snake-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---

apiVersion: v1
kind: service
metadata:
  name: snake-service
  namespace: mySpace
spec:
  type: LoadBalancer
  selector:
    app: snake-pod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
