apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: /mnt/data/grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitoring
  name: grafana
  labels:
    name: grafana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-pod
  template:
    metadata:
      labels:
        app: grafana-pod
    spec:
      containers:
        - name: Grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: loadBalancer
  selector:
    app: grafana-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30004
